In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import Model, layers
from tensorflow.keras.models import Sequential
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [3]:
def convolution_layer_test(filters, kernel_size, s=1, p='valid', input_size=[1,64,64,3]):
    inputs = tf.random.normal(input_size)
    print('input size: ', inputs.shape)
    conv = tf.keras.layers.Conv2D(filters, kernel_size, strides=s, padding=p)
    outputs = conv(inputs)
    print('output size: ', outputs.shape)

In [4]:
convolution_layer_test(10, 3) # (W-F+2P)/s+1

input size:  (1, 64, 64, 3)
output size:  (1, 62, 62, 10)


2022-07-27 15:39:07.451078: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-07-27 15:39:07.451182: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (piai-Precision-7920-Tower): /proc/driver/nvidia/version does not exist
2022-07-27 15:39:07.454172: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [7]:
convolution_layer_test(10, 11, s=6, p = 'valid', input_size=[1,128,128,3]) # (128-11)/6+1

input size:  (1, 128, 128, 3)
output size:  (1, 20, 20, 10)


In [19]:
def pooling_layer_test(pool_size, s=1, p='valid', input_size=[1,4,4,1]):
    inputs = tf.random.normal(input_size)
    print('input: ', inputs)
    pool = tf.keras.layers.MaxPool2D(pool_size, strides=s, padding=p)
    outputs = pool(inputs)
    print('output: ', outputs)

In [34]:
pooling_layer_test(2,2)

input:  tf.Tensor(
[[[[ 1.1857686 ]
   [-1.1816387 ]
   [ 0.5059694 ]
   [ 0.44601083]]

  [[-0.19596359]
   [ 0.05605837]
   [-0.19713336]
   [ 0.1451701 ]]

  [[ 1.6328409 ]
   [-1.1992745 ]
   [ 0.2554219 ]
   [ 0.17318861]]

  [[-1.3330626 ]
   [ 0.6904897 ]
   [ 0.02229808]
   [ 1.4717507 ]]]], shape=(1, 4, 4, 1), dtype=float32)
output:  tf.Tensor(
[[[[1.1857686]
   [0.5059694]]

  [[1.6328409]
   [1.4717507]]]], shape=(1, 2, 2, 1), dtype=float32)
